# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/kevinburke/go-bindata",
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false

[[prune.project]]
  name = "github.com/kevinburke/go-bindata"
  non-go = false
  unused-packages = false

# Operator internals

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.12.5"

[[override]]
  name = "github.com/kevinburke/go-bindata"
  version = "v3.13.0"

[[override]]
  name = "github.com/openshift/api"
  revision = "31ed61683850951801cddda5b075fcb24a500532"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "v0.28.0"

[[override]]
  name = "github.com/openshift/library-go"
  revision = "cef3bac303c956844aa15215630d26b1e0a1085a"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.16.26"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "v0.1.10"
