# Inform openshift-monitoring about which endpoint to use for metrics collection
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  # name is set at runtime
  namespace: openshift-ingress
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: https
    path: /metrics
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      # serverName is set at runtime
  namespaceSelector:
    matchNames:
    - openshift-ingress
  selector: {}
